services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=moyugongming'
      - 'MONGO_INITDB_ROOT_PASSWORD=a1436381036'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongodb:/data/db
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=moyugongming'
      - 'MYSQL_PASSWORD=a1436381036'
      - 'MYSQL_ROOT_PASSWORD=a1436381036'
      - 'MYSQL_ROOT_USER=root'
    ports:
      - '61444:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
